package Kursovi4koff;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.sun.org.glassfish.gmbal.Impact;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author asass
 */
public class KGraphics extends javax.swing.JFrame {

    /**
     * Creates new form KGraphics
     */
    public KGraphics() {
        initComponents();
    }
    /*Инициализация глобальных переменных*/
    int width;
    int heigth;
    int solve;
    Field field;
    List<Answer>myAnswer=new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    /*Контейнер DrawPanel, переопределяющий метод paintComponent, ответственный за отрисовку*/
    public class DrawPanel extends JPanel {
        private static final long serialVersionUID = 1L;
        @Override
        public void paintComponent(Graphics g){
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;
            /*Отрисовка полей матрицы*/
            for(int i=0; i< heigth; i++){
                for(int j=0; j< width; j++) {
                    if(field.matrix[i][j]==0)   //Если поле свободно, красим в желтый
                        g2d.setColor(Color.yellow);
                    else                        //Иначе в зеленый
                        g2d.setColor(Color.blue);
                    g2d.fillRect(50 + j * 40, 50+i*40, 40, 40);
                }
            }
            g2d.setColor(Color.black);
            Font font= new Font("Arial", Font.CENTER_BASELINE, 30);
            g2d.setFont(font);
            /*Отрисовка символов координат*/
            for(int i=0; i<heigth; i++)
                g2d.drawString(String.valueOf(i+1), 13, 80+i*40);
            for(int i=0; i<width; i++)
                g2d.drawString(String.valueOf(i+1), 55+i*40, 45);
            /*Если задача была решена, выполняем отрисовку целевых прямоугольников*/
            if(solve==1){
                g2d.setColor(Color.red);
                solve=0;
                for(Answer i:myAnswer){
                    int x1=i.x1-1;
                    int y1=i.y1-1;
                    int x2=i.x2-1;
                    int y2=i.y2-1;
                    for(int m=y1; m<=y2;m++) {
                        for (int n = x1; n <= x2; n++)
                            g2d.fillRect(50 + n * 40, 50 + m * 40, 40, 40);
                    }
                    /*Выделяем прямоугольник толстой линией*/
                    g2d.setColor(Color.black);
                    g2d.setStroke(new BasicStroke(5));
                    g2d.drawLine(50+x1*40, 50+y1*40, 50+x1*40, 50+(y2+1)*40);
                    g2d.drawLine(50+x1*40, 50+y1*40, 50+(x2+1)*40, 50+y1*40);
                    g2d.drawLine(50+(x2+1)*40, 50+(y2+1)*40, 50+(x2+1)*40, 50+y1*40);
                    g2d.drawLine(50+(x2+1)*40, 50+(y2+1)*40, 50+x1*40, 50+(y2+1)*40);
                    g2d.setColor(Color.red);
                }
            }
            g2d.setColor(Color.black);
            g2d.setStroke(new BasicStroke(1));
            /*Отрисовка координатной сетки*/
            for(int i=0; i<heigth+2; i++)
                g2d.drawLine(10, 10 + i * 40, 50 + width * 40, 10 + i * 40);
            for(int i=0; i<width+2; i++)
                g2d.drawLine(10+i*40, 10, 10+i*40, 50+heigth*40 );
        }

    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    /*Инициализация компонентов*/
    private void initComponents() {

        jPanel1 = new DrawPanel();  //Контейнер
        jButton1 = new javax.swing.JButton();//
        jButton2 = new javax.swing.JButton();//
        jButton3 = new javax.swing.JButton();// КНОПКИ
        jButton4 = new javax.swing.JButton();//
        jScrollPane2 = new javax.swing.JScrollPane();//Панель прокрутки
        jTextArea1 = new javax.swing.JTextArea();//Зона текста

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Insert field");
        jButton1.setName(""); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton2.setText("Place obstacles");
        jButton2.setMaximumSize(new java.awt.Dimension(50, 20));
        jButton2.setMinimumSize(new java.awt.Dimension(50, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton3.setText("Find rectangle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton4.setText("Delete obstacles");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jButton1.getAccessibleContext().setAccessibleDescription("Insert field");

        pack();
    }// </editor-fold>

    /*Назначение действия на 1ю кнопку.*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String sWidth = JOptionPane.showInputDialog("Enter the width of the field");//Диалоговое окно для введения ширины поля
        width= Integer.parseInt(sWidth);
        String sHeigth = JOptionPane.showInputDialog("Enter the heigth of the field");//Диалоговое окно для введения длины поля
        heigth= Integer.parseInt(sHeigth);
        field= new Field(width, heigth);//Создание объекта класса поле
        jPanel1.repaint();//Отрисовка
    }
    /*Назначение действия на вторую кнопку*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.addMouseListener(new MouseAdapter() { //Вешаем прослушиватель мыши на контейнер
            int mouseX;
            int mouseY;
            @Override
            public void mouseClicked(MouseEvent e){ //Задание действия по клику мыши на поле
                mouseX = e.getX();//
                mouseY = e.getY();// ПОЛУЧАЕМ КООРДИНАТЫ КУРСОРА В МОМЕНТ КЛИКА
                int x= (mouseX-50)/40;
                int y= (mouseY-50)/40;// ВЫЧИСЛЯЕМ КООРДИНАТЫ ЯЧЕЙКИ, В КОТОРОЙ БЫЛ ПРОИЗВЕДЕН КЛИК
                if(x<field.width && y<field.heigth) {
                    field.matrix[y][x]=1;   //Помечаем ячейку как заняткю
                    jPanel1.repaint();      //Раскрашиваем ее в другой цвет
                }
            }
        });
    }
    /*Назначения действия на 3 кнопку*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        myAnswer= Algorhytms.findRectangle(field); //Решаем задачу
        solve=1;
        int number=1;
        jTextArea1.setText(null);//Очищаем текстовое окно
        jPanel1.repaint();//Закрашиваем полученный(ые) прямоугольники
        jTextArea1.append("Square= "+String.valueOf(myAnswer.get(0).square)+"\n");
        for(Answer i: myAnswer){    //Выводим в текстовое окно необходимые данные
            jTextArea1.append( "Rectangle "+ String.valueOf(number)+"\n x1= "+ String.valueOf(i.x1)+", y1= "+String.valueOf(i.y1)+"\n x2= "+ String.valueOf(i.x2)+", y2= "+String.valueOf(i.y2)+"\n");
            number++;
        }
    }
    /*Назначение действия на 4 кнопку*/
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel1.addMouseListener(new MouseAdapter() {   //Вешаем прослушиватель мыши на контейнер
            int mouseX;
            int mouseY;
            @Override
            public void mouseClicked(MouseEvent e){
                mouseX = e.getX();//
                mouseY = e.getY();// ПОЛУЧАЕМ КООРДИНАТЫ КУРСОРА В МОМЕНТ КЛИКА
                int x= (mouseX-50)/40;//
                int y= (mouseY-50)/40;// ВЫЧИСЛЯЕМ КООРДИНАТЫ ЯЧЕЙКИ, В КОТОРОЙ БЫЛ ПРОИЗВЕДЕН КЛИК
                if(x<field.width && y<field.heigth) {
                    field.matrix[y][x]=0;//Помечаем ячейку как свободную
                    jPanel1.repaint();//Раскрашиваем ее в прежний цвет
                }
            }
        });
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
               /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KGraphics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KGraphics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private DrawPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration
}
